application:
  ignored:
    urls:
      - /user/get-captcha
      - /user/register
      - /user/authenticate
      - /user/forgot-password
      - /user/confirm-otp
      - /user/reset-password
      - /user/test
      - /v3/api-docs
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /slider/all
      - /kommunicate/bot/get-bot-active

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
spring:
  thymeleaf:
    check-template-location: false
  quartz:
    job-store-type: jdbc
  application:
    name: toeicute-api
  boot:
    admin:
      client:
        url: "${SPRING_BOOT_ADMIN_URL:http://127.0.0.1:8080/api}"
        instance:
          service-url: "${SPRING_BOOT_ADMIN_URL:http://127.0.0.1:8080/api}"
          name: "${spring.application.name}"
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "${GOOGLE_CLIENT_ID:adsa}"
            clientSecret: "${GOOGLE_CLIENT_SECRET:dsadsd}"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: "${FACEBOOK_CLIENT_ID:132}"
            clientSecret: "${FACEBOOK_CLIENT_SECRET:1321}"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: "https://www.facebook.com/v3.0/dialog/oauth"
            tokenUri: "https://graph.facebook.com/v3.0/oauth/access_token"
            userInfoUri: "https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)"
  ai:
    vertex:
      ai:
        gemini:
          project-id: "${GEMINI_PROJECT_ID:123456}"
          location: "${GEMINI_LOCATION:12356}"
        api-key: "${GEMINI_API_KEY:123456}"
        chat:
          model: chat-bison-001
    openai:
      api-key: "${OPENAI_API_KEY:sk-1234567890}"
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:toeicute}?useUnicode=true&createDatabaseIfNotExist=true"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:1234}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  api-docs:
    path: /toeicute/api-docs
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: "${JWT_SECRET:872c871a1ab996919a3e97145ece2418bb837cadbd69387d96cd45eef831f239}"
  expiration: "${JWT_EXPIRATION:86400000}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false
logging:
  level:
    root: info
  file:
    name: target/toeicute.log

