server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
spring:
  application:
    name: toeicute-api
  boot:
    admin:
      client:
        url: "http://${HOST:localhost}:8080/api"
        instance:
          service-url: "http://${HOST:localhost}:8080/api"

  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:toeicute}?useUnicode=true&createDatabaseIfNotExist=true"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:1234}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  api-docs:
    path: /toeicute/api-docs
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: "${JWT_SECRET:872c871a1ab996919a3e97145ece2418bb837cadbd69387d96cd45eef831f239}"
  expiration: "${JWT_EXPIRATION:86400000}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: info
  file:
    name: target/toeicute.log

firebase:
  project-id: "${FIREBASE_PROJECT_ID:toeicute-70460}"
  token-key: "${FIREBASE_TOKEN_KEY:toeicute-upload}"
  bucket-name: "${FIREBASE_BUCKET_NAME:toeicute-70460.appspot.com}"
ipinfo:
  token: "${IPINFO_TOKEN:b1324b9ae149de}"

BOT_AI_URL: "${API_AI:https://llamastudio.dev/api/cls40w5460001l2087o43vxsy}"
openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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

GOOGLE_TRANSLATE_API: "${GOOGLE_TRANSLATE_URL:https://translate.google.com/translate_a/single?client=at&dt=t&dt=ld&dt=qca&dt=rm&dt=bd&dj=1&hl=%25s&ie=UTF-8&oe=UTF-8&inputm=2&otf=2&iid=1dd3b944-fa62-4b55-b330-74909a99969e&}"
REV_AI_TOKEN: "${REVAI_ACCESS_TOKEN:02x7qBPWLMBrrDZPKWallLiYEyxJ8Hz_JdqqVWgIaracvN8t9jtP_Xypu7QKlEDKDaXHwHN7_ArTSTKnsULjDqHKNQFtw}"


